import { createHash, randomBytes } from "node:crypto";
import { readdir } from "node:fs/promises";
import path from "node:path";
import { withWorkspaceLifecycleLock } from "../process/registry.js";
import {
  getLifecycleDocumentPath,
  RECONCILIATION_CONTEXT_AUTHORITY_POLICY,
  RECONCILIATION_CONTEXT_AUTHORITY_SCHEMA_V2,
  RECONCILIATION_CONTEXT_CUSTODY_POLICY,
  RECONCILIATION_CONTEXT_IDENTITY_POLICY,
  RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_POLICY,
  RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_SCHEMA_V1,
  RECONCILIATION_CONTEXT_PUBLICATION_MARKER_POLICY,
  RECONCILIATION_CONTEXT_PUBLICATION_MARKER_SCHEMA_V1,
  readLifecycleDocument,
  writeLifecycleDocument,
} from "../state/lifecycle-persistence.js";

const AUTHORITY_ID_PATTERN = /^[a-f0-9]{64}$/u;

interface ReconciliationContextAuthority {
  schemaVersion: typeof RECONCILIATION_CONTEXT_AUTHORITY_SCHEMA_V2;
  version: 2;
  authorityId: string;
  authorityDigest: string;
  phase: "committed";
}

interface ReconciliationContextPublicationRecord {
  schemaVersion: typeof RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_SCHEMA_V1 | typeof RECONCILIATION_CONTEXT_PUBLICATION_MARKER_SCHEMA_V1;
  version: 1;
  authorityId: string;
  authorityDigest: string;
}

export class ReconciliationContextIdentityError extends Error {
  constructor() {
    super("Durable reconciliation context identity is unavailable.");
    this.name = "ReconciliationContextIdentityError";
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function exactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  const actual = Object.keys(value).sort();
  return actual.length === keys.length && actual.every((key, index) => key === keys[index]);
}

function parseAuthority(value: unknown): ReconciliationContextAuthority | null {
  if (!isRecord(value) || !exactKeys(value, ["authorityDigest", "authorityId", "phase", "schemaVersion", "version"])) return null;
  if (
    value.schemaVersion !== RECONCILIATION_CONTEXT_AUTHORITY_SCHEMA_V2 ||
    value.version !== 2 ||
    typeof value.authorityId !== "string" ||
    !AUTHORITY_ID_PATTERN.test(value.authorityId) ||
    typeof value.authorityDigest !== "string" ||
    !AUTHORITY_ID_PATTERN.test(value.authorityDigest) ||
    value.authorityDigest !== authorityDigest(value.authorityId) ||
    value.phase !== "committed"
  ) return null;
  return {
    schemaVersion: RECONCILIATION_CONTEXT_AUTHORITY_SCHEMA_V2,
    version: 2,
    authorityId: value.authorityId,
    authorityDigest: value.authorityDigest,
    phase: "committed",
  };
}

function parsePublicationRecord(
  value: unknown,
  schemaVersion: ReconciliationContextPublicationRecord["schemaVersion"],
): ReconciliationContextPublicationRecord | null {
  if (!isRecord(value) || !exactKeys(value, ["authorityDigest", "authorityId", "schemaVersion", "version"])) return null;
  if (
    value.schemaVersion !== schemaVersion ||
    value.version !== 1 ||
    typeof value.authorityId !== "string" ||
    !AUTHORITY_ID_PATTERN.test(value.authorityId) ||
    typeof value.authorityDigest !== "string" ||
    !AUTHORITY_ID_PATTERN.test(value.authorityDigest) ||
    value.authorityDigest !== authorityDigest(value.authorityId)
  ) return null;
  return { schemaVersion, version: 1, authorityId: value.authorityId, authorityDigest: value.authorityDigest };
}

function sameAuthority(left: ReconciliationContextPublicationRecord | ReconciliationContextAuthority, right: ReconciliationContextPublicationRecord | ReconciliationContextAuthority): boolean {
  return left.authorityId === right.authorityId && left.authorityDigest === right.authorityDigest;
}

function authorityDigest(authorityId: string): string {
  return createHash("sha256").update(authorityId, "utf8").digest("hex");
}

const RECONCILIATION_CONTEXT_CUSTODY_POLICIES = [
  RECONCILIATION_CONTEXT_AUTHORITY_POLICY,
  RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_POLICY,
  RECONCILIATION_CONTEXT_PUBLICATION_MARKER_POLICY,
  RECONCILIATION_CONTEXT_IDENTITY_POLICY,
  RECONCILIATION_CONTEXT_CUSTODY_POLICY,
] as const;

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

/**
 * This is deliberately limited to the five custody records and the exact
 * sidecar names generated by lifecycle persistence.  It is not a workspace
 * scan: unrelated files cannot prevent a legitimate fresh Core instance.
 */
async function assertNoReconciliationContextCustodyResidue(workspaceRoot: string): Promise<void> {
  const authorityPath = getLifecycleDocumentPath(workspaceRoot, RECONCILIATION_CONTEXT_AUTHORITY_POLICY);
  const stateDirectory = path.dirname(authorityPath);
  let entries: string[];
  try {
    entries = await readdir(stateDirectory);
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return;
    throw new ReconciliationContextIdentityError();
  }
  const residueNames = new Set<string>();
  const writerTempPatterns: RegExp[] = [];
  for (const policy of RECONCILIATION_CONTEXT_CUSTODY_POLICIES) {
    const fileName = path.basename(getLifecycleDocumentPath(workspaceRoot, policy));
    residueNames.add(`${fileName}.bak`);
    residueNames.add(`${fileName}.v${policy.legacyVersion}.bak`);
    residueNames.add(`${fileName}.migrate.json`);
    residueNames.add(`${fileName}.migrate.tmp`);
    writerTempPatterns.push(new RegExp(`^${escapeRegex(fileName)}\\.\\d+\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.tmp$`, "u"));
  }
  if (entries.some((entry) => residueNames.has(entry) || writerTempPatterns.some((pattern) => pattern.test(entry)))) {
    throw new ReconciliationContextIdentityError();
  }
}

/**
 * This is called only while Core creates its server.  A request only consumes
 * the resolved value; it cannot create, replace, or recover identity state.
 */
export async function initializeReconciliationContextIdentity(workspaceRoot: string): Promise<string> {
  try {
    return await withWorkspaceLifecycleLock(workspaceRoot, async () => {
      await assertNoReconciliationContextCustodyResidue(workspaceRoot);
      const authority = await readLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_AUTHORITY_POLICY, {
        parseCurrent: parseAuthority,
        parseLegacy: () => null,
        allowCrashBackup: false,
      });
      const journal = await readLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_POLICY, {
        parseCurrent: (value) => parsePublicationRecord(value, RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_SCHEMA_V1),
        parseLegacy: () => null,
        allowCrashBackup: false,
      });
      const marker = await readLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_PUBLICATION_MARKER_POLICY, {
        parseCurrent: (value) => parsePublicationRecord(value, RECONCILIATION_CONTEXT_PUBLICATION_MARKER_SCHEMA_V1),
        parseLegacy: () => null,
        allowCrashBackup: false,
      });
      const publishMarker = async (record: ReconciliationContextAuthority) => {
        await writeLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_PUBLICATION_MARKER_POLICY, {
          schemaVersion: RECONCILIATION_CONTEXT_PUBLICATION_MARKER_SCHEMA_V1,
          version: 1,
          authorityId: record.authorityId,
          authorityDigest: record.authorityDigest,
        }, {
          parseCurrent: (value) => parsePublicationRecord(value, RECONCILIATION_CONTEXT_PUBLICATION_MARKER_SCHEMA_V1),
          parseLegacy: () => null,
          serialize: (document) => document,
        });
      };
      if (marker.document) {
        if (authority.document && journal.document && sameAuthority(marker.document, authority.document) && sameAuthority(marker.document, journal.document)) {
          return authority.document.authorityId;
        }
        throw new ReconciliationContextIdentityError();
      }
      if (marker.inspection.classification !== "missing" || journal.inspection.classification !== "missing" && !journal.document) {
        throw new ReconciliationContextIdentityError();
      }
      if (journal.document) {
        if (authority.inspection.classification === "missing") {
          const stagedAuthority: ReconciliationContextAuthority = {
            schemaVersion: RECONCILIATION_CONTEXT_AUTHORITY_SCHEMA_V2,
            version: 2,
            authorityId: journal.document.authorityId,
            authorityDigest: journal.document.authorityDigest,
            phase: "committed",
          };
          await writeLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_AUTHORITY_POLICY, stagedAuthority, {
            parseCurrent: parseAuthority, parseLegacy: () => null, serialize: (document) => document,
          });
          await publishMarker(stagedAuthority);
          return stagedAuthority.authorityId;
        }
        if (authority.document && sameAuthority(authority.document, journal.document)) {
          await publishMarker(authority.document);
          return authority.document.authorityId;
        }
        throw new ReconciliationContextIdentityError();
      }
      if (authority.inspection.classification !== "missing") throw new ReconciliationContextIdentityError();
      // The split v1 pair must never be silently adopted or replaced.  Even a
      // semantically matching pair cannot prove it was not interrupted.
      const [legacyIdentity, legacyCustody] = await Promise.all([
        readLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_IDENTITY_POLICY, {
          parseCurrent: () => null,
          parseLegacy: () => null,
          allowCrashBackup: false,
        }),
        readLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_CUSTODY_POLICY, {
          parseCurrent: () => null,
          parseLegacy: () => null,
          allowCrashBackup: false,
        }),
      ]);
      if (legacyIdentity.inspection.classification !== "missing" || legacyCustody.inspection.classification !== "missing") {
        throw new ReconciliationContextIdentityError();
      }
      const authorityId = randomBytes(32).toString("hex");
      const nextAuthority: ReconciliationContextAuthority = {
        schemaVersion: RECONCILIATION_CONTEXT_AUTHORITY_SCHEMA_V2,
        version: 2,
        authorityId,
        authorityDigest: authorityDigest(authorityId),
        phase: "committed",
      };
      await writeLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_POLICY, {
        schemaVersion: RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_SCHEMA_V1,
        version: 1,
        authorityId,
        authorityDigest: nextAuthority.authorityDigest,
      }, {
        parseCurrent: (value) => parsePublicationRecord(value, RECONCILIATION_CONTEXT_PUBLICATION_JOURNAL_SCHEMA_V1),
        parseLegacy: () => null,
        serialize: (document) => document,
      });
      await writeLifecycleDocument(workspaceRoot, RECONCILIATION_CONTEXT_AUTHORITY_POLICY, nextAuthority, {
        parseCurrent: parseAuthority,
        parseLegacy: () => null,
        serialize: (document) => document,
      });
      await publishMarker(nextAuthority);
      return authorityId;
    });
  } catch (error) {
    if (error instanceof ReconciliationContextIdentityError) throw error;
    throw new ReconciliationContextIdentityError();
  }
}
