/* Root-owned Darwin host-runner service.  The daemon creates the resident
 * primary itself and retains primary identity plus one-shot grants. */
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/proc_info.h>
#include <sys/codesign.h>
#include <libproc.h>
#include <mach/mach.h>
#include <bsm/libbsm.h>
#include <CommonCrypto/CommonDigest.h>
#include <Security/Security.h>
#include <fcntl.h>
#include <errno.h>
#include <spawn.h>
#include <unistd.h>
#include <xpc/xpc.h>
#include <stdbool.h>
#include <stdint.h>
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
extern char **environ;
#define SHA_LEN CC_SHA256_DIGEST_LENGTH
#define MAX_GRANTS 64
static const char STATE_DIR[] = "/var/db/service-lasso/host-runner";
static char client_requirement[4096];
typedef struct { pid_t pid; uint64_t birth; pid_t parent; audit_token_t audit; unsigned char image_sha256[SHA_LEN]; } primary_t;
typedef struct { int fd; dev_t dev; ino_t ino; unsigned char sha256[SHA_LEN]; } expected_t;
/* A grant is one daemon-owned job transaction.  The daemon, never the client,
 * snapshots every expected object into held descriptors at issuance and tears
 * all of them down with the one-use capability. */
typedef struct { bool live; dev_t dev; ino_t ino; int daemon_fd; expected_t parent_object; expected_t leaf_object; audit_token_t peer; pid_t pid; pid_t parent; uint64_t birth; unsigned char image_sha256[SHA_LEN]; uint64_t nonce; time_t expiry; } grant_t;
static grant_t grants[MAX_GRANTS]; static primary_t primary; static int receipt_fd = -1;
static char self_path[PROC_PIDPATHINFO_MAXSIZE];
static void reap_primary_on_exit(int signal_number) { if (primary.pid > 1) { (void)kill(primary.pid, SIGTERM); while (waitpid(primary.pid, NULL, 0) < 0) { if (errno != EINTR) break; } } _exit(128 + signal_number); }
static void receipt(const char *event, bool accepted) { char line[192]; int n = snprintf(line, sizeof line, "event=%s accepted=%d primary=%d birth=%llu\\n", event, accepted ? 1 : 0, primary.pid, (unsigned long long)primary.birth); if (receipt_fd >= 0 && n > 0) (void)write(receipt_fd, line, (size_t)n); }
static bool hash_fd(int fd, unsigned char digest[SHA_LEN]) { unsigned char buffer[8192]; CC_SHA256_CTX ctx; ssize_t n; if (fd < 0 || lseek(fd, 0, SEEK_SET) < 0) return false; CC_SHA256_Init(&ctx); while ((n = read(fd, buffer, sizeof buffer)) > 0) CC_SHA256_Update(&ctx, buffer, (CC_LONG)n); if (n < 0 || lseek(fd, 0, SEEK_SET) < 0) return false; CC_SHA256_Final(digest, &ctx); return true; }
static bool protected_root_regular_fd(int fd, unsigned char digest[SHA_LEN]) { struct stat st; return fd >= 0 && fstat(fd, &st) == 0 && S_ISREG(st.st_mode) && st.st_uid == 0 && (st.st_mode & 0077) == 0 && st.st_nlink == 1 && hash_fd(fd, digest); }
static bool load_client_requirement(void) { char path[PATH_MAX]; int fd; ssize_t n; unsigned char digest[SHA_LEN]; if (snprintf(path, sizeof path, "%s/client-requirement", STATE_DIR) >= (int)sizeof path || (fd = open(path, O_RDONLY|O_NOFOLLOW|O_CLOEXEC)) < 0 || !protected_root_regular_fd(fd, digest) || (n = read(fd, client_requirement, sizeof client_requirement - 1)) <= 0 || n >= (ssize_t)sizeof client_requirement - 1 || memchr(client_requirement, '\0', (size_t)n) != NULL) { if (fd >= 0) close(fd); return false; } client_requirement[n] = '\0'; close(fd); return true; }
static bool hold_created_object(const char *name, const void *bytes, size_t length, expected_t *object) { char path[PATH_MAX]; struct stat st; int fd = -1; if (object == NULL || length == 0 || snprintf(path, sizeof path, "%s/jobs/%s", STATE_DIR, name) >= (int)sizeof path || (fd = open(path, O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC, 0600)) < 0 || write(fd, bytes, length) != (ssize_t)length || fsync(fd) != 0 || close(fd) != 0 || (object->fd = open(path, O_RDONLY|O_NOFOLLOW|O_CLOEXEC)) < 0 || !protected_root_regular_fd(object->fd, object->sha256) || fstat(object->fd, &st) != 0) { if (fd >= 0) close(fd); if (object->fd >= 0) close(object->fd); object->fd = -1; return false; } object->dev = st.st_dev; object->ino = st.st_ino; return true; }
static bool expected_object_is_unchanged(const expected_t *object) { struct stat st; unsigned char digest[SHA_LEN]; return object->fd >= 0 && fstat(object->fd, &st) == 0 && st.st_dev == object->dev && st.st_ino == object->ino && protected_root_regular_fd(object->fd, digest) && memcmp(digest, object->sha256, SHA_LEN) == 0; }
/* Parent data must contain the authenticated leaf digest. Both were hashed through held FDs. */
static bool parent_binds_leaf(int parent_fd, const unsigned char leaf[SHA_LEN]) { unsigned char envelope[4 + SHA_LEN]; if (lseek(parent_fd, 0, SEEK_SET) < 0 || read(parent_fd, envelope, sizeof envelope) != (ssize_t)sizeof envelope || lseek(parent_fd, 0, SEEK_SET) < 0) return false; return memcmp(envelope, "SLHR", 4) == 0 && memcmp(envelope + 4, leaf, SHA_LEN) == 0; }
static bool durable_job_transition(uint64_t nonce, time_t expiry, const char *state) { char path[PATH_MAX], line[160]; int fd; int length; if (state == NULL || snprintf(path, sizeof path, "%s/jobs/journal", STATE_DIR) >= (int)sizeof path || (fd = open(path, O_WRONLY|O_APPEND|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0600)) < 0) return false; length = snprintf(line, sizeof line, "%016llx %llu %s\\n", (unsigned long long)nonce, (unsigned long long)expiry, state); bool ok = length > 0 && length < (int)sizeof line && write(fd, line, (size_t)length) == length && fsync(fd) == 0; close(fd); return ok; }
static bool create_daemon_job_outputs(uint64_t nonce, const unsigned char client_image[SHA_LEN], expected_t *parent, expected_t *leaf) { unsigned char leaf_bytes[4 + SHA_LEN + SHA_LEN + sizeof nonce], parent_bytes[4 + SHA_LEN]; char leaf_name[64], parent_name[64]; memcpy(leaf_bytes, "SLHO", 4); memcpy(leaf_bytes + 4, primary.image_sha256, SHA_LEN); memcpy(leaf_bytes + 4 + SHA_LEN, client_image, SHA_LEN); memcpy(leaf_bytes + 4 + SHA_LEN + SHA_LEN, &nonce, sizeof nonce); if (snprintf(leaf_name, sizeof leaf_name, "job-%016llx.output", (unsigned long long)nonce) >= (int)sizeof leaf_name || !hold_created_object(leaf_name, leaf_bytes, sizeof leaf_bytes, leaf)) return false; memcpy(parent_bytes, "SLHR", 4); memcpy(parent_bytes + 4, leaf->sha256, SHA_LEN); if (snprintf(parent_name, sizeof parent_name, "job-%016llx.inventory", (unsigned long long)nonce) >= (int)sizeof parent_name || !hold_created_object(parent_name, parent_bytes, sizeof parent_bytes, parent)) { close(leaf->fd); leaf->fd = -1; return false; } return true; }
static bool hash_pid_image(pid_t pid, unsigned char digest[SHA_LEN]) { char image[PROC_PIDPATHINFO_MAXSIZE]; int fd; if (proc_pidpath(pid, image, sizeof image) <= 0 || (fd = open(image, O_RDONLY|O_NOFOLLOW|O_CLOEXEC)) < 0) return false; bool ok = protected_root_regular_fd(fd, digest); close(fd); return ok; }
static bool strict_code_identity(pid_t pid, const char *requirement_text) { SecCodeRef code = NULL; SecRequirementRef requirement = NULL; CFNumberRef pid_number = CFNumberCreate(NULL, kCFNumberIntType, &pid); const void *keys[] = { kSecGuestAttributePid }; const void *values[] = { pid_number }; CFDictionaryRef attributes = CFDictionaryCreate(NULL, keys, values, 1, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks); OSStatus status = pid_number == NULL || attributes == NULL ? errSecParam : SecCodeCopyGuestWithAttributes(NULL, attributes, kSecCSDefaultFlags, &code); if (status == errSecSuccess) status = SecRequirementCreateWithString(CFStringCreateWithCString(NULL, requirement_text, kCFStringEncodingUTF8), kSecCSDefaultFlags, &requirement); if (status == errSecSuccess) status = SecCodeCheckValidity(code, kSecCSStrictValidate, requirement); if (requirement != NULL) CFRelease(requirement); if (code != NULL) CFRelease(code); if (attributes != NULL) CFRelease(attributes); if (pid_number != NULL) CFRelease(pid_number); return status == errSecSuccess; }
static bool primary_is_live_and_owned(void) { struct proc_bsdinfo info; int status = 0; mach_port_t task = MACH_PORT_NULL; audit_token_t token; mach_msg_type_number_t count = TASK_AUDIT_TOKEN_COUNT; unsigned char image[SHA_LEN]; if (primary.pid <= 1 || proc_pidinfo(primary.pid, PROC_PIDTBSDINFO, 0, &info, sizeof info) != sizeof info || (uint64_t)info.pbi_start_tvsec != primary.birth || info.pbi_ppid != getpid() || !hash_pid_image(primary.pid, image) || memcmp(image, primary.image_sha256, SHA_LEN) != 0) return false; if (task_for_pid(mach_task_self(), primary.pid, &task) != KERN_SUCCESS) return false; kern_return_t kr = task_info(task, TASK_AUDIT_TOKEN, (task_info_t)&token, &count); mach_port_deallocate(mach_task_self(), task); return kr == KERN_SUCCESS && count == TASK_AUDIT_TOKEN_COUNT && audit_token_to_pid(token) == primary.pid && memcmp(&token, &primary.audit, sizeof token) == 0 && csops(primary.pid, CS_OPS_STATUS, &status, sizeof status) == 0 && (status & CS_VALID) != 0 && (status & CS_HARD) != 0 && strict_code_identity(primary.pid, client_requirement); }
static bool capture_primary(pid_t pid, const unsigned char image[SHA_LEN]) { struct proc_bsdinfo info; mach_port_t task = MACH_PORT_NULL; mach_msg_type_number_t count = TASK_AUDIT_TOKEN_COUNT; if (proc_pidinfo(pid, PROC_PIDTBSDINFO, 0, &info, sizeof info) != sizeof info || info.pbi_ppid != getpid() || task_for_pid(mach_task_self(), pid, &task) != KERN_SUCCESS) return false; kern_return_t kr = task_info(task, TASK_AUDIT_TOKEN, (task_info_t)&primary.audit, &count); mach_port_deallocate(mach_task_self(), task); if (kr != KERN_SUCCESS || count != TASK_AUDIT_TOKEN_COUNT || audit_token_to_pid(primary.audit) != pid) return false; primary.pid = pid; primary.birth = (uint64_t)info.pbi_start_tvsec; primary.parent = info.pbi_ppid; memcpy(primary.image_sha256, image, SHA_LEN); return primary_is_live_and_owned(); }
static bool spawn_resident_primary(const unsigned char image[SHA_LEN]) { pid_t pid = 0; char *argv[] = { self_path, "--resident-primary", NULL }; if (posix_spawn(&pid, self_path, NULL, NULL, argv, environ) != 0) return false; for (int i = 0; i < 20; i++) { if (capture_primary(pid, image)) return true; usleep(10000); } (void)kill(pid, SIGTERM); return false; }
static void revoke_grant(grant_t *grant) { if (grant->live) (void)durable_job_transition(grant->nonce, grant->expiry, "revoked"); if (grant->daemon_fd >= 0) close(grant->daemon_fd); if (grant->parent_object.fd >= 0) close(grant->parent_object.fd); if (grant->leaf_object.fd >= 0) close(grant->leaf_object.fd); grant->daemon_fd = -1; grant->parent_object.fd = -1; grant->leaf_object.fd = -1; grant->live = false; }
static void revoke_peer(audit_token_t peer) { for (size_t i = 0; i < MAX_GRANTS; i++) if (grants[i].live && memcmp(&grants[i].peer, &peer, sizeof peer) == 0) revoke_grant(&grants[i]); }
static void revoke_expired(void) { time_t now = time(NULL); for (size_t i = 0; i < MAX_GRANTS; i++) if (grants[i].live && grants[i].expiry <= now) revoke_grant(&grants[i]); }
static bool reviewed_client(audit_token_t peer, struct proc_bsdinfo *info, unsigned char image[SHA_LEN]) { pid_t pid = audit_token_to_pid(peer); return client_requirement[0] != '\0' && audit_token_to_euid(peer) == 0 && pid > 1 && proc_pidinfo(pid, PROC_PIDTBSDINFO, 0, info, sizeof *info) == sizeof *info && hash_pid_image(pid, image) && strict_code_identity(pid, client_requirement); }
static int issue_capability(audit_token_t peer, uint64_t expiry, uint64_t *nonce) { int fds[2] = {-1, -1}; struct stat st; struct proc_bsdinfo info; unsigned char image[SHA_LEN]; expected_t parent = { .fd = -1 }, leaf = { .fd = -1 }; uint64_t fresh_nonce = (uint64_t)arc4random() << 32 | arc4random(); revoke_expired(); if (nonce == NULL || !primary_is_live_and_owned() || !reviewed_client(peer, &info, image) || expiry <= (uint64_t)time(NULL) || expiry > (uint64_t)time(NULL) + 60 || !create_daemon_job_outputs(fresh_nonce, image, &parent, &leaf) || !parent_binds_leaf(parent.fd, leaf.sha256) || !durable_job_transition(fresh_nonce, (time_t)expiry, "issued") || pipe(fds) != 0 || fstat(fds[1], &st) != 0) { if (parent.fd >= 0) close(parent.fd); if (leaf.fd >= 0) close(leaf.fd); if (fds[0] >= 0) close(fds[0]); if (fds[1] >= 0) close(fds[1]); return -1; } for (size_t i = 0; i < MAX_GRANTS; i++) if (!grants[i].live) { grants[i] = (grant_t){ .live=true, .dev=st.st_dev, .ino=st.st_ino, .daemon_fd=fds[0], .parent_object=parent, .leaf_object=leaf, .peer=peer, .pid=audit_token_to_pid(peer), .parent=info.pbi_ppid, .birth=(uint64_t)info.pbi_start_tvsec, .expiry=(time_t)expiry, .nonce=fresh_nonce }; memcpy(grants[i].image_sha256, image, SHA_LEN); *nonce = grants[i].nonce; return fds[1]; } close(parent.fd); close(leaf.fd); close(fds[0]); close(fds[1]); return -1; }
static bool consume_capability(int capability, audit_token_t peer) { struct stat st; struct proc_bsdinfo info; unsigned char image[SHA_LEN]; uint64_t nonce = 0; bool ok = false; revoke_expired(); if (capability < 0 || fstat(capability, &st) != 0 || !reviewed_client(peer, &info, image)) { if (capability >= 0) close(capability); return false; } for (size_t i = 0; i < MAX_GRANTS; i++) if (grants[i].live && grants[i].dev == st.st_dev && grants[i].ino == st.st_ino && memcmp(&grants[i].peer, &peer, sizeof peer) == 0) { ok = read(grants[i].daemon_fd, &nonce, sizeof nonce) == (ssize_t)sizeof nonce && nonce == grants[i].nonce && grants[i].pid == audit_token_to_pid(peer) && grants[i].parent == info.pbi_ppid && grants[i].birth == (uint64_t)info.pbi_start_tvsec && memcmp(grants[i].image_sha256, image, SHA_LEN) == 0 && expected_object_is_unchanged(&grants[i].parent_object) && expected_object_is_unchanged(&grants[i].leaf_object) && parent_binds_leaf(grants[i].parent_object.fd, grants[i].leaf_object.sha256) && durable_job_transition(grants[i].nonce, grants[i].expiry, "consumed"); revoke_grant(&grants[i]); break; } close(capability); return ok; }
static void handle_connection(xpc_connection_t peer) { xpc_connection_set_event_handler(peer, ^(xpc_object_t message) { audit_token_t peer_token; xpc_connection_get_audit_token(peer, &peer_token); if (xpc_get_type(message) == XPC_TYPE_ERROR) { revoke_peer(peer_token); receipt("disconnect-revoke", false); return; } if (xpc_get_type(message) != XPC_TYPE_DICTIONARY || audit_token_to_euid(peer_token) != 0) return; const char *operation = xpc_dictionary_get_string(message, "operation"); if (operation != NULL && strcmp(operation, "issue-grant") == 0) { uint64_t nonce = 0; int fd = issue_capability(peer_token, xpc_dictionary_get_uint64(message, "expires_at_unix"), &nonce); xpc_dictionary_set_fd(message, "capability_fd", fd); xpc_dictionary_set_data(message, "capability_nonce", &nonce, sizeof nonce); if (fd >= 0) close(fd); xpc_dictionary_set_bool(message, "accepted", fd >= 0); receipt("job-grant-issued", fd >= 0); xpc_connection_send_message(peer, message); return; } int capability = operation != NULL && strcmp(operation, "complete") == 0 ? xpc_dictionary_dup_fd(message, "capability_fd") : -1; bool ok = primary_is_live_and_owned() && consume_capability(capability, peer_token); xpc_dictionary_set_bool(message, "accepted", ok); receipt("job-completion", ok); xpc_connection_send_message(peer, message); }); xpc_connection_resume(peer); }
int main(int argc, char **argv) { struct stat state; char jobs_path[PATH_MAX]; struct sigaction action = { .sa_handler = reap_primary_on_exit }; if (argc == 2 && strcmp(argv[1], "--resident-primary") == 0) { for (;;) pause(); } if (argc != 3 || strcmp(argv[1], "--state-dir") != 0 || strcmp(argv[2], STATE_DIR) != 0 || geteuid() != 0 || lstat(STATE_DIR, &state) != 0 || !S_ISDIR(state.st_mode) || state.st_uid != 0 || (state.st_mode & 0077) != 0 || snprintf(jobs_path, sizeof jobs_path, "%s/jobs", STATE_DIR) >= (int)sizeof jobs_path || lstat(jobs_path, &state) != 0 || !S_ISDIR(state.st_mode) || state.st_uid != 0 || (state.st_mode & 0077) != 0 || proc_pidpath(getpid(), self_path, sizeof self_path) <= 0) return 64; (void)sigaction(SIGTERM, &action, NULL); (void)sigaction(SIGINT, &action, NULL); int image_fd = open(self_path, O_RDONLY | O_NOFOLLOW | O_CLOEXEC); unsigned char image[SHA_LEN]; if (image_fd < 0 || !protected_root_regular_fd(image_fd, image) || !load_client_requirement() || !spawn_resident_primary(image)) return 65; close(image_fd); char receipt_path[PATH_MAX]; if (snprintf(receipt_path, sizeof receipt_path, "%s/private-receipt.log", STATE_DIR) >= (int)sizeof receipt_path) return 66; receipt_fd = open(receipt_path, O_WRONLY|O_APPEND|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0600); if (receipt_fd < 0) return 67; if (fstat(receipt_fd, &state) != 0 || !S_ISREG(state.st_mode) || state.st_uid != 0 || (state.st_mode & 0077) != 0 || state.st_nlink != 1) return 68; receipt("daemon-ready", true); xpc_main(^(xpc_connection_t p) { handle_connection(p); }); return 0; }
