import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { classify, parseReceipt } from "../scripts/consume-admin-trusted-unlock-receipt.mjs";
const valid = JSON.stringify({ schema: "service-admin.trusted-unlock-receipt.v1", status: "observed", present: true, verified: false, localRoot: false, loading: true, unavailable: false });
test("AC-4BY.2 accepts only own closed receipt fields", () => { assert.equal(parseReceipt(valid)?.loading, true); assert.equal(parseReceipt({ get schema() { throw new Error("must not access getter"); } }), null); assert.deepEqual(classify([]), { classification: "missing" }); });
test("AC-4BY.2 preserves real subprocess failure while classifying every closed receipt outcome", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "admin-receipt-")); try { const consumer = fileURLToPath(new URL("../scripts/consume-admin-trusted-unlock-receipt.mjs", import.meta.url)); const run = async (line) => { const fixture = path.join(root, `${Math.random()}.mjs`), output = path.join(root, `${Math.random()}.json`); await writeFile(fixture, `await new Promise((resolve) => process.stderr.write(${JSON.stringify(line)}, resolve)); process.exitCode=7;`); const child = spawn(process.execPath, [consumer, "--receipt", output, "--", process.execPath, fixture], { stdio: "ignore" }); const code = await new Promise((resolve, reject) => { child.once("error", reject); child.once("close", resolve); }); return { code, trustedUnlock: JSON.parse(await readFile(output, "utf8")).trustedUnlock }; };
    const closed = await run(`${valid}\n`); assert.equal(closed.code, 7); assert.deepEqual(closed.trustedUnlock, { classification: "closed", receipt: JSON.parse(valid) });
    for (const line of ["", `${valid}{\n`, `${valid.replace("\"loading\":true", "\"loading\":true,\"private\":true")}\n`, `${valid.replace("\"loading\":true", "\"loading\":true,\"loading\":false")}\n`, `${valid}\n${valid}\n`]) assert.deepEqual((await run(line)).trustedUnlock, { classification: line ? "invalid" : "missing" });
  } finally { await rm(root, { recursive: true, force: true }); } });
