import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { preflightReleaseArchive, type ReleaseArchiveType } from "./release-archive-preflight.js";
import { withCrossProcessFileLock } from "../security/cross-process-file-lock.js";

export type StageState = "uploading" | "ready" | "rejected" | "expired" | "claimed" | "consumed" | "quarantined" | "cleaned" | "unknown";
export interface ReleaseIdentity { repo:string; releaseTag:string; commitSha:string; targetServiceId:string; platform:"win32"|"linux"|"darwin"; archiveType:ReleaseArchiveType; assetName:string; assetId:string; archiveBytes:number; archiveSha256:string; manifestSha256:string; releaseId:string; manifestAssetId?:string; checksumAssetId?:string|null; }
export interface StageResolver { resolve(input:{repo:string;releaseTag:string;commitSha:string;targetServiceId:string;platform:string}):Promise<ReleaseIdentity>; }
/** Direct child receives only the same persisted, Core-held byte object. */
export interface DirectChildImporter { import(input:{serviceId:string;bytes:Uint8Array;byteObjectId:string;archiveSha256:string;manifestSha256:string;releaseId:string;targetSha:string;workspaceId:string}):Promise<"completed"|"conflict"|"unknown">; }
export interface TransferActor { id:string; workspaceId:string; canConfigure:boolean; }
interface Chunk { ordinal:number; start:number; end:number; digest:string; fingerprint:string; bytes:string; }
interface Stage { id:string; actorId:string; workspaceId:string; state:StageState; identity:ReleaseIdentity; tokenHash:string; confirmationHash:string|null; confirmationExpiresAt:number|null; expiresAt:number; chunks:Chunk[]; received:number; archiveDigestPrefix:string|null; manifestDigestPrefix:string; byteObject:{id:string;bytes:string;sha256:string;size:number}|null; operation:{id:string;key:string;state:"completed"|"conflict"|"unknown";stageDigest:string;targetServiceId:string}|null; terminalAt:number|null; }
interface Store { version:2; stages:Stage[]; }
const MAX_BYTES=64*1024*1024, MAX_CHUNKS=64, MAX_ENTRIES=1024, MAX_EXPANDED=128*1024*1024;
const UPLOAD_MS=30*60_000, READY_MS=10*60_000, CONFIRM_MS=10*60_000, REJECTED_MS=24*60*60_000, QUARANTINE_MS=7*24*60*60_000;
const hash=(v:Uint8Array|string)=>createHash("sha256").update(v).digest("hex");
const opaque=(p:string,n:number)=>p+randomBytes(n).toString("base64url");
const equal=(a:string,b:string)=>a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const idPattern=/^[a-z0-9](?:[a-z0-9._-]{0,62}[a-z0-9])?$/, repoPattern=/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/, shaPattern=/^[a-f0-9]{40}$/, digestPattern=/^[a-f0-9]{64}$/;
const keyPattern=/^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$/, stagePattern=/^stg_[A-Za-z0-9_-]{32}$/, tokenPattern=/^sut_[A-Za-z0-9_-]{43}$/, confirmationPattern=/^scf_[A-Za-z0-9_-]{32}$/;
const active=(state:StageState)=>!["consumed","cleaned"].includes(state);

export class StagedServiceTransfer {
  constructor(private readonly workspaceRoot:string,private readonly resolver:StageResolver,private readonly importer:DirectChildImporter,private readonly now:()=>number=Date.now) {}
  private statePath(){return path.join(this.workspaceRoot,".service-lasso","operator","staged-service-transfers.json");}
  private async locked<T>(work:(store:Store)=>Promise<T>):Promise<T>{const file=this.statePath();return await withCrossProcessFileLock(file+".lock",async()=>{let store:Store={version:2,stages:[]};try{const value=JSON.parse(await readFile(file,"utf8")) as Store;if(value.version!==2||!Array.isArray(value.stages))throw new Error();store=value;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw new TransferError("registration_unavailable",503);}this.recover(store);const result=await work(store);await mkdir(path.dirname(file),{recursive:true});const temp=file+"."+randomBytes(8).toString("hex");await writeFile(temp,JSON.stringify(store),{mode:0o600});await rename(temp,file);return result;},{unavailableMessage:"staged transfer state unavailable"});}
  private recover(store:Store){const now=this.now();for(const s of store.stages){if((s.state==="uploading"||s.state==="ready")&&s.expiresAt<=now){s.state="expired";s.terminalAt=s.expiresAt;s.confirmationHash=null;s.confirmationExpiresAt=null;}if(s.confirmationExpiresAt!==null&&s.confirmationExpiresAt<=now){s.confirmationHash=null;s.confirmationExpiresAt=null;}if((s.state==="rejected"||s.state==="expired")&&s.terminalAt!==null&&s.terminalAt+REJECTED_MS<=now){s.state="cleaned";s.chunks=[];s.byteObject=null;}if(s.state==="quarantined"&&s.terminalAt!==null&&s.terminalAt+QUARANTINE_MS<=now){s.state="cleaned";s.chunks=[];s.byteObject=null;}}}
  private actor(a:TransferActor){if(!a.canConfigure||!a.id||!a.workspaceId)throw new TransferError("forbidden",403);}
  private find(store:Store,a:TransferActor,id:string){this.actor(a);if(!stagePattern.test(id))throw new TransferError("stage_not_found",404);const s=store.stages.find(x=>x.id===id&&x.actorId===a.id&&x.workspaceId===a.workspaceId);if(!s)throw new TransferError("stage_not_found",404);return s;}
  private chunkBytes(s:Stage){return Math.min(1024*1024,Math.max(256*1024,Math.ceil(s.identity.archiveBytes/MAX_CHUNKS)));}
  private use(stages:Stage[]){return stages.filter(s=>active(s.state)).reduce((a,s)=>({stages:a.stages+1,bytes:a.bytes+s.identity.archiveBytes,chunks:a.chunks+MAX_CHUNKS,entries:a.entries+MAX_ENTRIES,expanded:a.expanded+MAX_EXPANDED}),{stages:0,bytes:0,chunks:0,entries:0,expanded:0});}
  private quota(store:Store,a:TransferActor,i:ReleaseIdentity){const add=(r:{stages:number;bytes:number;chunks:number;entries:number;expanded:number})=>({stages:r.stages+1,bytes:r.bytes+i.archiveBytes,chunks:r.chunks+MAX_CHUNKS,entries:r.entries+MAX_ENTRIES,expanded:r.expanded+MAX_EXPANDED});const x=add(this.use(store.stages.filter(s=>s.actorId===a.id))),w=add(this.use(store.stages.filter(s=>s.workspaceId===a.workspaceId)));if(x.stages>8||x.bytes>256*1024*1024||x.chunks>512||x.entries>8192||x.expanded>1024*1024*1024||w.stages>64||w.bytes>1024*1024*1024||w.chunks>4096||w.entries>65536||w.expanded>8*1024*1024*1024)throw new TransferError("stage_quota_exceeded",429);}
  async create(a:TransferActor,input:{targetServiceId:string;provenance:{repo:string;releaseTag:string;commitSha:string};platform:string;manifestSchemaVersion:string}){this.actor(a);if(!idPattern.test(input.targetServiceId)||!repoPattern.test(input.provenance.repo)||!shaPattern.test(input.provenance.commitSha)||!["win32","linux","darwin"].includes(input.platform)||input.manifestSchemaVersion!=="service-lasso.service-manifest/v1")throw new TransferError("invalid_request",400);const i=await this.resolver.resolve({...input.provenance,targetServiceId:input.targetServiceId,platform:input.platform});if(i.targetServiceId!==input.targetServiceId||i.repo!==input.provenance.repo||i.releaseTag!==input.provenance.releaseTag||i.commitSha!==input.provenance.commitSha||i.platform!==input.platform||i.archiveType!=="zip"||i.archiveBytes<1||i.archiveBytes>MAX_BYTES||!digestPattern.test(i.archiveSha256)||!digestPattern.test(i.manifestSha256)||!i.releaseId||!i.assetId||!i.assetName)throw new TransferError(i.archiveType!=="zip"?"unapproved_release":"release_provenance_unavailable",i.archiveType!=="zip"?403:503);return await this.locked(async store=>{this.quota(store,a,i);const token=opaque("sut_",32),id=opaque("stg_",24),expires=this.now()+UPLOAD_MS;const s:Stage={id,actorId:a.id,workspaceId:a.workspaceId,state:"uploading",identity:i,tokenHash:hash(token),confirmationHash:null,confirmationExpiresAt:null,expiresAt:expires,chunks:[],received:0,archiveDigestPrefix:null,manifestDigestPrefix:i.manifestSha256.slice(0,12),byteObject:null,operation:null,terminalAt:null};store.stages.push(s);return {stageId:id,state:"uploading" as const,archiveBytes:i.archiveBytes,chunkBytes:this.chunkBytes(s),uploadToken:token,expiresAt:new Date(expires).toISOString()};});}
  async upload(a:TransferActor,id:string,ordinal:number,token:string,digest:string,bytes:Uint8Array,range?:{start:number;end:number;total:number}){if(!Number.isInteger(ordinal)||ordinal<0||ordinal>=MAX_CHUNKS||!tokenPattern.test(token)||!digestPattern.test(digest))throw new TransferError("invalid_request",400);return await this.locked(async store=>{const s=this.find(store,a,id);if(s.state!=="uploading"||s.expiresAt<=this.now()||!equal(s.tokenHash,hash(token)))throw new TransferError("stage_not_found",404);const unit=this.chunkBytes(s),start=ordinal*unit,expected=Math.min(unit,s.identity.archiveBytes-start),end=start+expected-1;if(expected<1||bytes.length!==expected||(range&&(range.start!==start||range.end!==end||range.total!==s.identity.archiveBytes)))throw new TransferError("chunk_sequence_conflict",409);const fp=hash(`${id}\0${a.id}\0${ordinal}\0${start}\0${end}\0${s.identity.archiveBytes}\0${digest}\0${Buffer.from(bytes).toString("base64")}`),prior=s.chunks[ordinal];if(prior){if(prior.fingerprint===fp)return;throw new TransferError("chunk_sequence_conflict",409);}if(ordinal!==s.chunks.length||hash(bytes)!==digest)throw new TransferError("chunk_sequence_conflict",409);s.chunks.push({ordinal,start,end,digest,fingerprint:fp,bytes:Buffer.from(bytes).toString("base64")});s.received+=bytes.length;});}
  async finalize(a:TransferActor,id:string){return await this.locked(async store=>{const s=this.find(store,a,id);if(s.state!=="uploading"||s.expiresAt<=this.now()||s.received!==s.identity.archiveBytes||s.chunks.length!==Math.ceil(s.identity.archiveBytes/this.chunkBytes(s)))throw new TransferError("digest_mismatch",409);const bytes=Buffer.concat(s.chunks.map(c=>Buffer.from(c.bytes,"base64")));if(!equal(hash(bytes),s.identity.archiveSha256)||!preflightReleaseArchive({bytes,archiveType:s.identity.archiveType}).ok){s.state="rejected";s.terminalAt=this.now();throw new TransferError("archive_unsafe",409);}s.byteObject={id:`sbo_${hash(`${s.id}\0${s.identity.archiveSha256}`).slice(0,32)}`,bytes:bytes.toString("base64"),sha256:s.identity.archiveSha256,size:bytes.length};s.chunks=[];s.state="ready";s.expiresAt=this.now()+READY_MS;s.archiveDigestPrefix=s.identity.archiveSha256.slice(0,12);return this.public(s);});}
  async confirmation(a:TransferActor,id:string){return await this.locked(async store=>{const s=this.find(store,a,id);if(s.state!=="ready"||s.expiresAt<=this.now())throw new TransferError("stage_not_found",404);const c=opaque("scf_",24),e=this.now()+CONFIRM_MS;s.confirmationHash=hash(c);s.confirmationExpiresAt=e;return {confirmationId:c,stageId:id,expiresAt:new Date(e).toISOString(),archiveDigestPrefix:s.archiveDigestPrefix,code:"confirmation_issued"};});}
  private sameIdentity(a:ReleaseIdentity,b:ReleaseIdentity){return a.repo===b.repo&&a.releaseTag===b.releaseTag&&a.commitSha===b.commitSha&&a.targetServiceId===b.targetServiceId&&a.platform===b.platform&&a.archiveType===b.archiveType&&a.assetName===b.assetName&&a.assetId===b.assetId&&a.archiveBytes===b.archiveBytes&&a.archiveSha256===b.archiveSha256&&a.manifestSha256===b.manifestSha256&&a.releaseId===b.releaseId&&(a.manifestAssetId??null)===(b.manifestAssetId??null)&&(a.checksumAssetId??null)===(b.checksumAssetId??null);}
  async register(a:TransferActor,id:string,confirmation:string,key:string){if(!confirmationPattern.test(confirmation)||!keyPattern.test(key))throw new TransferError("invalid_request",400);const identity=await this.locked(async store=>this.find(store,a,id).identity);let resolved:ReleaseIdentity;try{resolved=await this.resolver.resolve({repo:identity.repo,releaseTag:identity.releaseTag,commitSha:identity.commitSha,targetServiceId:identity.targetServiceId,platform:identity.platform});}catch{throw new TransferError("release_provenance_unavailable",503);}if(!this.sameIdentity(identity,resolved))throw new TransferError("release_binding_mismatch",409);const claim=await this.locked(async store=>{const s=this.find(store,a,id);if(s.operation){if(s.operation.key===key&&s.operation.stageDigest===s.identity.archiveSha256&&s.operation.targetServiceId===s.identity.targetServiceId)return {s,replayed:true};throw new TransferError("idempotency_conflict",409);}if(s.state!=="ready"||s.expiresAt<=this.now()||!s.confirmationHash||!s.confirmationExpiresAt||s.confirmationExpiresAt<=this.now()||!equal(s.confirmationHash,hash(confirmation))||!s.byteObject)throw new TransferError("stage_not_found",404);s.state="claimed";s.confirmationHash=null;s.confirmationExpiresAt=null;s.operation={id:opaque("sto_",24),key,state:"unknown",stageDigest:s.identity.archiveSha256,targetServiceId:s.identity.targetServiceId};return {s,replayed:false};});if(!claim.replayed){let outcome:"completed"|"conflict"|"unknown"="unknown";try{const o=claim.s.byteObject!;outcome=await this.importer.import({serviceId:claim.s.identity.targetServiceId,bytes:Buffer.from(o.bytes,"base64"),byteObjectId:o.id,archiveSha256:o.sha256,manifestSha256:claim.s.identity.manifestSha256,releaseId:claim.s.identity.releaseId,targetSha:claim.s.identity.commitSha,workspaceId:claim.s.workspaceId});}catch{}await this.locked(async store=>{const s=this.find(store,a,id);if(s.operation){s.operation.state=outcome;s.state=outcome==="completed"?"consumed":outcome==="conflict"?"quarantined":"unknown";s.terminalAt=s.state==="unknown"?null:this.now();}});}const stage=await this.locked(async store=>this.find(store,a,id));return {operation:stage.operation,replayed:claim.replayed,status:stage.state};}
  async status(a:TransferActor,id:string){return await this.locked(async store=>this.public(this.find(store,a,id)));}
  private public(s:Stage){return {stageId:s.id,state:s.state,targetServiceId:s.identity.targetServiceId,archiveBytes:s.identity.archiveBytes,receivedBytes:s.received,receivedChunks:s.chunks.length,archiveDigestPrefix:s.archiveDigestPrefix,manifestDigestPrefix:s.manifestDigestPrefix,provenance:{repo:s.identity.repo,releaseTag:s.identity.releaseTag,commitSha:s.identity.commitSha},platform:s.identity.platform,assetName:s.identity.assetName,expiresAt:new Date(s.expiresAt).toISOString(),code:s.state};}
}
export class TransferError extends Error {constructor(readonly code:string,readonly statusCode:number,message="Staged service transfer request denied."){super(message);}}
