import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { preflightReleaseArchive, type ReleaseArchiveType } from "./release-archive-preflight.js";
import { withCrossProcessFileLock } from "../security/cross-process-file-lock.js";

export type StageState = "uploading" | "ready" | "rejected" | "claimed" | "consumed" | "unknown";
export interface ReleaseIdentity { repo: string; releaseTag: string; commitSha: string; targetServiceId: string; platform: "win32" | "linux" | "darwin"; archiveType: ReleaseArchiveType; assetName: string; assetId: string; archiveBytes: number; archiveSha256: string; manifestSha256: string; releaseId: string; }
export interface StageResolver { resolve(input: { repo: string; releaseTag: string; commitSha: string; targetServiceId: string; platform: string }): Promise<ReleaseIdentity>; }
export interface DirectChildImporter { import(input: { serviceId: string; bytes: Uint8Array; archiveSha256: string; manifestSha256: string; releaseId: string; targetSha: string }): Promise<"completed" | "conflict" | "unknown">; }
export interface TransferActor { id: string; workspaceId: string; canConfigure: boolean; }
interface Stage { id: string; actorId: string; workspaceId: string; state: StageState; identity: ReleaseIdentity; tokenHash: string; confirmationHash: string | null; expiresAt: number; chunks: string[]; received: number; archiveDigestPrefix: string | null; manifestDigestPrefix: string; operation: { id: string; key: string; state: "completed" | "conflict" | "unknown" } | null; }
interface Store { version: 1; stages: Stage[]; }
const MAX_BYTES = 64 * 1024 * 1024, MAX_CHUNKS = 64;
const hash = (value: Uint8Array | string) => createHash("sha256").update(value).digest("hex");
const opaque = (prefix: string, bytes: number) => prefix + randomBytes(bytes).toString("base64url");
const equal = (left: string, right: string) => left.length === right.length && timingSafeEqual(Buffer.from(left), Buffer.from(right));
const idPattern = /^[a-z0-9](?:[a-z0-9._-]{0,62}[a-z0-9])?$/;
const repoPattern = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/, shaPattern = /^[a-f0-9]{40}$/, digestPattern = /^[a-f0-9]{64}$/;
export class StagedServiceTransfer {
  constructor(private readonly workspaceRoot: string, private readonly resolver: StageResolver, private readonly importer: DirectChildImporter) {}
  private statePath() { return path.join(this.workspaceRoot, ".service-lasso", "operator", "staged-service-transfers.json"); }
  private async locked<T>(work: (store: Store) => Promise<T>): Promise<T> { const file = this.statePath(); return await withCrossProcessFileLock(file + ".lock", async () => { let store: Store = { version: 1, stages: [] }; try { const value = JSON.parse(await readFile(file, "utf8")) as Store; if (value.version !== 1 || !Array.isArray(value.stages)) throw new Error(); store = value; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new TransferError("registration_unavailable", 503); } const result = await work(store); await mkdir(path.dirname(file), { recursive: true }); const temp = file + "." + randomBytes(8).toString("hex"); await writeFile(temp, JSON.stringify(store), { mode: 0o600 }); await rename(temp, file); return result; }, { unavailableMessage: "staged transfer state unavailable" }); }
  private actor(actor: TransferActor) { if (!actor.canConfigure || !actor.id || !actor.workspaceId) throw new TransferError("forbidden", 403); }
  async create(actor: TransferActor, input: { targetServiceId: string; provenance: { repo: string; releaseTag: string; commitSha: string }; platform: string; manifestSchemaVersion: string }) {
    this.actor(actor); if (!idPattern.test(input.targetServiceId) || !repoPattern.test(input.provenance.repo) || !shaPattern.test(input.provenance.commitSha) || !["win32","linux","darwin"].includes(input.platform) || input.manifestSchemaVersion !== "service-lasso.service-manifest/v1") throw new TransferError("invalid_request", 400);
    const identity = await this.resolver.resolve({ ...input.provenance, targetServiceId: input.targetServiceId, platform: input.platform }); if (identity.archiveBytes < 1 || identity.archiveBytes > MAX_BYTES || !digestPattern.test(identity.archiveSha256) || !digestPattern.test(identity.manifestSha256)) throw new TransferError("release_provenance_unavailable", 503);
    return await this.locked(async store => { const used = store.stages.filter(s => s.actorId === actor.id && !["consumed"].includes(s.state)).reduce((sum,s) => sum + s.identity.archiveBytes, 0); if (used + identity.archiveBytes > 256 * 1024 * 1024 || store.stages.filter(s => s.actorId === actor.id && s.state !== "consumed").length >= 8) throw new TransferError("stage_quota_exceeded", 429); const token = opaque("sut_", 32), id = opaque("stg_", 24); const chunkBytes = Math.min(1024 * 1024, Math.max(256 * 1024, Math.ceil(identity.archiveBytes / MAX_CHUNKS))); store.stages.push({ id, actorId: actor.id, workspaceId: actor.workspaceId, state: "uploading", identity, tokenHash: hash(token), confirmationHash: null, expiresAt: Date.now() + 30 * 60_000, chunks: [], received: 0, archiveDigestPrefix: null, manifestDigestPrefix: identity.manifestSha256.slice(0,12), operation: null }); return { stageId: id, state: "uploading", archiveBytes: identity.archiveBytes, chunkBytes, uploadToken: token, expiresAt: new Date(Date.now() + 30 * 60_000).toISOString() }; }); }
  private find(store: Store, actor: TransferActor, id: string) { this.actor(actor); const stage = store.stages.find(s => s.id === id && s.actorId === actor.id); if (!stage) throw new TransferError("stage_not_found", 404); if (stage.workspaceId !== actor.workspaceId) throw new TransferError("stage_not_found", 404); return stage; }
  async upload(actor: TransferActor, id: string, ordinal: number, token: string, digest: string, bytes: Uint8Array) { if (!Number.isInteger(ordinal) || ordinal < 0 || ordinal >= MAX_CHUNKS || !digestPattern.test(digest)) throw new TransferError("invalid_request",400); return await this.locked(async store => { const stage = this.find(store, actor, id); if (stage.state !== "uploading" || stage.expiresAt < Date.now()) throw new TransferError("stage_not_found",404); if (!equal(stage.tokenHash, hash(token))) throw new TransferError("stage_not_found",404); if (hash(bytes) !== digest) throw new TransferError("chunk_sequence_conflict",409); if (ordinal !== stage.chunks.length) { if (ordinal < stage.chunks.length && stage.chunks[ordinal] === Buffer.from(bytes).toString("base64")) return; throw new TransferError("chunk_sequence_conflict",409); } if (stage.received + bytes.length > stage.identity.archiveBytes) throw new TransferError("chunk_sequence_conflict",409); stage.chunks.push(Buffer.from(bytes).toString("base64")); stage.received += bytes.length; }); }
  async finalize(actor: TransferActor, id: string) { return await this.locked(async store => { const stage = this.find(store,actor,id); if (stage.state !== "uploading" || stage.received !== stage.identity.archiveBytes) throw new TransferError("digest_mismatch",409); const bytes = Buffer.concat(stage.chunks.map(c => Buffer.from(c,"base64"))); if (!equal(hash(bytes),stage.identity.archiveSha256)) { stage.state="rejected"; throw new TransferError("digest_mismatch",409); } if (stage.identity.archiveType !== "zip") throw new TransferError("archive_unsafe",409); const preflight = preflightReleaseArchive({bytes,archiveType:stage.identity.archiveType}); if (!preflight.ok) { stage.state="rejected"; throw new TransferError("archive_unsafe",409); } stage.state="ready"; stage.expiresAt=Date.now()+10*60_000; stage.archiveDigestPrefix=stage.identity.archiveSha256.slice(0,12); return this.public(stage); }); }
  async confirmation(actor: TransferActor,id:string) { return await this.locked(async store => { const stage=this.find(store,actor,id); if(stage.state!=="ready"||stage.expiresAt<Date.now()) throw new TransferError("stage_not_found",404); const credential=opaque("scf_",24); stage.confirmationHash=hash(credential); return {confirmationId:credential,stageId:id,expiresAt:new Date(Date.now()+10*60_000).toISOString(),archiveDigestPrefix:stage.archiveDigestPrefix,code:"confirmation_issued"}; }); }
  async register(actor: TransferActor,id:string,confirmation:string,key:string) { if(!/^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$/.test(key)) throw new TransferError("invalid_request",400); const claim=await this.locked(async store=>{const stage=this.find(store,actor,id); if(stage.operation){ if(stage.operation.key===key)return {stage,replayed:true}; throw new TransferError("idempotency_conflict",409); } if(stage.state!=="ready"||!stage.confirmationHash||!equal(stage.confirmationHash,hash(confirmation)))throw new TransferError("stage_not_found",404); stage.state="claimed";stage.confirmationHash=null;stage.operation={id:opaque("sto_",24),key,state:"unknown"};return {stage,replayed:false};}); if(!claim.replayed){const bytes=Buffer.concat(claim.stage.chunks.map(c=>Buffer.from(c,"base64"))); const outcome=await this.importer.import({serviceId:claim.stage.identity.targetServiceId,bytes,archiveSha256:claim.stage.identity.archiveSha256,manifestSha256:claim.stage.identity.manifestSha256,releaseId:claim.stage.identity.releaseId,targetSha:claim.stage.identity.commitSha}); await this.locked(async store=>{const stage=this.find(store,actor,id); if(stage.operation)stage.operation.state=outcome; stage.state=outcome==="completed"?"consumed":"unknown";}); } return {operation:claim.stage.operation,replayed:claim.replayed}; }
  async status(actor: TransferActor,id:string) { return await this.locked(async store=>this.public(this.find(store,actor,id))); }
  private public(stage:Stage) { return {stageId:stage.id,state:stage.state,targetServiceId:stage.identity.targetServiceId,archiveBytes:stage.identity.archiveBytes,receivedBytes:stage.received,receivedChunks:stage.chunks.length,archiveDigestPrefix:stage.archiveDigestPrefix,manifestDigestPrefix:stage.manifestDigestPrefix,platform:stage.identity.platform,assetName:stage.identity.assetName,expiresAt:new Date(stage.expiresAt).toISOString()}; }
}
export class TransferError extends Error { constructor(readonly code:string,readonly statusCode:number,message="Staged service transfer request denied.") {super(message);} }

